# Sets up infrastructure where Nginx handles TLS and
# static content. Nginx proxies API requests to the
# server. The server is connected to a PostgreSQL
# database.
#
# see https://docs.docker.com/compose/compose-file/
#
version: '2'
services:
   web:
      image: nginx
      volumes:
         - ./www:/srv/openeth/www:ro
         - ./log:/srv/openeth/log:rw
         - ./certificates:/etc/ssl/certs:ro
         - ./empty:/var/empty:ro
         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      links:
         - api
         #- len
      ports:
         - "80:80"
         - "443:443"
   api:
      image: recmo/postgrest
      links:
         - dbm
      environment:
         POSTGREST_JWT_SECRET: 'Uz5Nlzgo28cGmYgC1yyAhyBmjb'
         PG_ENV_POSTGRES_USER: 'authenticator'
         POSTGREST_ANONYMOUS: 'anonymous'
         PG_ENV_POSTGRES_PASSWORD: 'vGsg4-Nxkn0xpSFRCthXDN'
         PG_ENV_POSTGRES_DB: 'openeth'
         PG_PORT_5432_TCP_ADDR: 'dbm'
         PG_PORT_5432_TCP_PORT: '5432'
         POSTGREST_MAX_ROWS: '1000000'
         POSTGREST_POOL: '200'
   dbm:
      image: postgres:9.5
      volumes:
         - ./database:/docker-entrypoint-initdb.d:ro
         - ./data:/var/lib/postgresql/:rw
      environment:
         POSTGRES_DB: 'openeth'
         POSTGRES_PASSWORD: 'EmSH7bIXL9si4cWx4Iyw'
   #log:
   #   image: 
   #len:
      #image: dockette/letsencrypt
      #volumes:
         #- ./certificates:/var/www/certs:rw
      #environment:
         #DOMAINS: 'openeth.com'
         #EMAIL: 'openeth-len@mytwopi.com'
