# Sets up infrastructure where Nginx handles TLS and
# static content. Nginx proxies API requests to the
# server. The server is connected to a PostgreSQL
# database.
#
# see https://docs.docker.com/compose/compose-file/
#
version: '2'
services:
   web:
      image: nginx
      volumes:
         - ./www:/srv/openeth/www:ro
         - ./log:/srv/openeth/log:rw
         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      links:
         - server
         - letsencrypt
      ports:
         - "8080:80"
   server:
      image: recmo/postgrest
      links:
         - db
      environment:
         POSTGREST_JWT_SECRET: '<INSERT Auth0 JWT SECRET HERE>'
         PG_ENV_POSTGRES_USER: 'authenticator'
         POSTGREST_ANONYMOUS: 'anonymous'
         PG_ENV_POSTGRES_PASSWORD: 'vGsg4-Nxkn0xpSFRCthXDN'
         PG_ENV_POSTGRES_DB: 'openeth'
         PG_PORT_5432_TCP_ADDR: 'db'
         PG_PORT_5432_TCP_PORT: '5432'
   db:
      image: postgres:9.5
      volumes:
         - ./database:/docker-entrypoint-initdb.d:ro
         - ./data:/var/lib/postgresql/:rw
      environment:
         POSTGRES_DB: 'openeth'
         POSTGRES_PASSWORD: 'EmSH7bIXL9si4cWx4Iyw'
   letsencrypt:
      image: dockette/letsencrypt
      volumes:
         - ./certificates:/var/www/certs:rw
      environment:
         DOMAINS: 'openeth.com'
         EMAIL: 'openeth-admin@2Ï€.com'
