version: '2'
services:
   web:
      restart: always
      ports:
         - "80:80"
         - "443:443"
      environment:
         DOMAINS:                  'staging.example.com'
   api:
      restart: always
   dbm:
      restart: always
   len:
      restart: always
      environment:
         DOMAINS:                  'staging.example.com'
         EMAIL:                    'len@example.com'
